### PR TITLE
Rename function and update README with correct name

### PR DESCRIPTION
**Pull request by chaudum**
client.pushRandomized -> client.pushParameterized

https://github.com/grafana/xk6-loki/blob/main/client.go#L173

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>

### CODE REVIEW

**Review by cyriltovena — APPROVED** [review]
LGTM

**Comment by chaudum** [comment]
Based on feedback from @KMiller-Grafana I renamed the function from `pushParametrized()` to `pushParameterized()`, see commit https://github.com/grafana/xk6-loki/pull/23/commits/983fb593b325bda5c681386e4bc203f9ea37bc55

**Review by KMiller-Grafana — APPROVED** [review]
My review has no standing, but LGTM.  Thanks for the change.

**Review by cyriltovena — APPROVED** [review]
LGTM

**Pull request merged**
